# Name of workflow
name: CI | Lint | SonarQube

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build
        run: |
          make install
          make build
        env:
          CI: true

      - name: Run linter
        run: make lint

    
    #   - name: SonarQube Scan
    #     uses: SonarSource/sonarqube-scan-action@v5
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #     with:
    #       args: >
    #         -Dsonar.projectKey=Dmitry-Khodanitsky_connect-four
    #         -Dsonar.organization=dmitry-khodanitsky
    #         -Dsonar.coverage.exclusions=**/*
    #         -Dsonar.tests=
    #         -Dsonar.test.inclusions=
    #         -Dsonar.test.exclusions=
    #         -Dsonar.javascript.lcov.reportPaths=
    #         -Dsonar.testExecutionReportPaths=
          